# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8bf0d185701e0afe66fedc5e8173720086e2c9478466d3f7237f429c72086a8b7ca490b524993d97e0369bc2681ecf7f1613d541277ec160c0621ae0c75025a

test:
  secret_key_base: 74506785952807bad5722e5a352ba08340f7f0a70bb8cd597ecc79588d3fdcaa0a9bff6980ac9e15ffcda7a2df840b13eccb72dc1fb9ee528c792b229c057b7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
